import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import BlogNavbar from '@/components/blog-navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-white flex h-screen w-screen flex-col items-center justify-between ">
          <BlogNavbar position='flex' />
          {children}
        </main>
      </body>
    </html>
  )
}
